<?php
use Illuminate\Support\Facades\{DB,Crypt};
use Illuminate\Support\Str;
use App\Services\Dashboard\{DesktopDashboardBootstrap,DesktopDashboardDevices,DesktopDashboardJournal,DesktopDashboardReconciliation,DesktopDashboardReviewDeletion};

// A closure keeps fixture variables out of the original shared HTTP origin/session scope.
(function() use($database,$ownerStage,$stage,$ownerDevice,$ownerLink,$remoteDevice,$link,$env,$application,$httpPort,$http,$profile,$pdo,$origin){
    $seed=function(int $id,int $restaurant=100,int $order=1,int $user=20){DB::table('reviews')->insert(['id'=>$id,'resturant_id'=>$restaurant,'order_id'=>$order,'user_id'=>$user,'rate'=>5,'created_at'=>'2020-01-01 00:00:00','updated_at'=>'2020-01-02 00:00:00']);};
    $switch=function(string $db,bool $local=false){config(['database.connections.mysql.database'=>$db,'desktop_dashboard.local'=>$local]);DB::purge();};
    $command=function(string $uuid)use($ownerDevice){$row=DB::table('desktop_dashboard_commands')->where('command_id',$uuid)->first();$result=json_decode(Crypt::decryptString($row->local_result_cipher),true);return ['command_id'=>$uuid,'actor_id'=>1,'route_name'=>$row->route_name,'payload'=>json_decode(Crypt::decryptString($row->command_cipher),true),'local_result'=>$result['result'],'local_references'=>$result['references'],'dependencies'=>json_decode($row->dependencies,true),'occurred_at'=>\Carbon\Carbon::parse($row->created_at,'UTC')->toIso8601String()];};
    $reject=function(callable $work,int $status,string $message){try{$work();throw new RuntimeException('Review operation unexpectedly succeeded.');}catch(\Symfony\Component\HttpKernel\Exception\HttpException $error){verify($error->getStatusCode()===$status,$message);}};
    $switch($database);$seed(91001);$seed(91002,101,2,21);
    $scoped=app(DesktopDashboardBootstrap::class)->export(app(DesktopDashboardDevices::class)->device($link['token']));
    verify(array_column($scoped['tables']['reviews']['rows'],'id')===[91001]&&$scoped['coverage']['full_dashboard']===false,'Review bootstrap includes only the enrolled F restaurant and keeps full dashboard coverage false');
    $switch($ownerStage,true);$seed(91001);$seed(91002,101,2,21);$seed(91003);$seed(91004);$seed(91005);
    DB::table('media')->insert(['id'=>91001,'model_type'=>\App\Models\Review::class,'model_id'=>91001,'collection_name'=>'review','name'=>'retained','file_name'=>'retained.png','mime_type'=>'image/png','disk'=>'public','conversions_disk'=>'public','size'=>1,'manipulations'=>'[]','custom_properties'=>'{}','generated_conversions'=>'{}','responsive_images'=>'{}']);
    $preserved=['order'=>(array)DB::table('orders')->where('id',1)->first(),'user'=>(array)DB::table('users')->where('id',20)->first(),'restaurant'=>(array)DB::table('resturants')->where('id',100)->first(),'media'=>(array)DB::table('media')->where('id',91001)->first()];
    $localEnv=$env;$localEnv['DB_DATABASE']=$ownerStage;$localEnv['DESKTOP_DASHBOARD_LOCAL']='true';
    $web=proc_open([PHP_BINARY,'-S','127.0.0.1:'.$httpPort,'-t',$application.'/public',$application.'/desktop/router.php'],[['pipe','r'],['file',$profile.'/web.log','a'],['file',$profile.'/web.log','a']],$pipes,$application,$localEnv);
    $operations=[];
    try{
        for($n=0;$n<100;$n++){if($http('/_desktop/health')[0]===200)break;usleep(50000);}
        [$status,$page]=$http('/admin/notifications');preg_match('/name="csrf-token" content="([^"]+)"/',$page,$csrf);verify($status===200&&isset($csrf[1]),'the original local session supplies real Review-delete CSRF');
        $form=['_token'=>$csrf[1],'_method'=>'DELETE','_desktop_command'=>(string)Str::uuid()];$before=DB::table('desktop_dashboard_commands')->count();
        [$status,$body,$headers]=$http('/admin/resturant_reviews/91001',$form,['Referer: '.$origin.'/admin/resturants/100']);
        verify($status===302&&in_array('Location: '.$origin.'/admin/resturants/100',$headers,true)&&!DB::table('reviews')->where('id',91001)->exists()&&DB::table('desktop_dashboard_commands')->count()===$before+1,'the original Review controller deletes exactly its row with one encrypted local command');
        verify($http('/admin/resturant_reviews/91001',$form)[0]===302&&DB::table('desktop_dashboard_commands')->count()===$before+1,'a lost local Review-delete redirect replays after the Review ID has disappeared');
        foreach($preserved as $kind=>$row){$table=['order'=>'orders','user'=>'users','restaurant'=>'resturants','media'=>'media'][$kind];verify((array)DB::table($table)->where('id',$row['id'])->first()===$row,'Review deletion preserves the original '.$kind.' row, including balances/rating/media');}
        $saved=$command($form['_desktop_command']);verify(count($saved['payload']['facts']['review_before']['row'])===7&&$saved['payload']['facts']['review_before']['row']['updated_at']==='2020-01-02 00:00:00'&&$saved['local_result']['http']['status']===302,'the encrypted before-state includes every Review column and the original redirect outcome');$operations[]=$saved;
        DB::table('users')->where('id',1)->update(['status'=>'disabled']);verify($http('/admin/resturant_reviews/91001',$form,['Accept: application/json'])[0]===403,'a disabled local actor cannot use a saved deleted-Review reply');DB::table('users')->where('id',1)->update(['status'=>'accepted']);
        DB::table('users')->where('id',1)->update(['owner_resturant_id'=>101]);verify($http('/admin/resturant_reviews/91001',$form,['Accept: application/json'])[0]===403,'a saved local Review reply checks the current enrolled restaurant relationship');DB::table('users')->where('id',1)->update(['owner_resturant_id'=>null]);
        DB::table('users')->where('id',1)->update(['app_scope'=>'go_admin']);verify($http('/admin/resturant_reviews/91001',$form)[0]===302,'an enrolled central GO administrator retains the original admin guard for an F Review without invented app-scope or delete grants');DB::table('users')->where('id',1)->update(['app_scope'=>'fasakhansta']);
        $bad=$form;$bad['_desktop_command']=(string)Str::uuid();verify($http('/admin/resturant_reviews/999999',$bad,['Accept: application/json'])[0]===404,'an unknown local Review keeps its original404 and creates no success command');
        $bad=$form;$bad['_desktop_command']=(string)Str::uuid();$bad['rate']=1;verify($http('/admin/resturant_reviews/91003',$bad,['Accept: application/json'])[0]===422&&DB::table('reviews')->where('id',91003)->exists(),'Review deletion cannot silently accept an unrelated update field');
        $bad=$form;$bad['_desktop_command']=(string)Str::uuid();$before=DB::table('desktop_dashboard_commands')->count();
        verify($http('/admin/resturant_reviews/91005',$bad,['Accept: application/json','X-Fasakhansta-Command: '.Str::uuid()])[0]===409&&DB::table('reviews')->where('id',91005)->exists()&&DB::table('desktop_dashboard_commands')->count()===$before,'conflicting local Review header and form UUIDs cannot delete or journal under an ambiguous identity');
        $bad['_desktop_command']=[(string)Str::uuid()];verify($http('/admin/resturant_reviews/91005',$bad,['Accept: application/json','X-Fasakhansta-Command: '.Str::uuid()])[0]===422&&DB::table('reviews')->where('id',91005)->exists()&&DB::table('desktop_dashboard_commands')->count()===$before,'a non-scalar local Review UUID is validated before conversion and cannot delete or journal');
        foreach([91003,91004] as $id){$next=$form;$next['_desktop_command']=(string)Str::uuid();verify($http('/admin/resturant_reviews/'.$id,$next)[0]===302,'the original controller prepares an immutable Review replay fixture');$operations[]=$command($next['_desktop_command']);}
        DB::unprepared("CREATE TRIGGER reject_review_journal BEFORE INSERT ON desktop_dashboard_commands FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='fixture Review journal failure'");
        try{$next=$form;$next['_desktop_command']=(string)Str::uuid();verify($http('/admin/resturant_reviews/91005',$next,['Accept: application/json'])[0]===500&&DB::table('reviews')->where('id',91005)->exists(),'failure to save the local command rolls back the original Review deletion');}finally{DB::unprepared('DROP TRIGGER reject_review_journal');}
    }finally{fclose($pipes[0]);proc_terminate($web);proc_close($web);}
    $switch($database);$seed(91003);$seed(91004);
    $actor=\App\Models\User::withoutGlobalScopes()->findOrFail(1);verify(!$actor->getAllPermissions()->pluck('name')->contains('resturant-delete'),'Review replay fixture has no original restaurant-delete permission');
    $receipt=app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[0]);verify($receipt===app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[0])&&!DB::table('reviews')->where('id',91001)->exists(),'Review reconciliation invokes the original controller once and returns an identical lost-response receipt');
    DB::table('users')->where('id',1)->update(['owner_resturant_id'=>101]);$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[0]),403,'a stored server Review receipt requires the current actor restaurant scope before deduplication');DB::table('users')->where('id',1)->update(['owner_resturant_id'=>null]);
    DB::table('desktop_dashboard_devices')->where('id',$remoteDevice->id)->update(['enabled'=>false]);$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[0]),401,'a revoked current device cannot obtain the saved Review receipt');DB::table('desktop_dashboard_devices')->where('id',$remoteDevice->id)->update(['enabled'=>true]);
    $original=(array)DB::table('reviews')->where('id',91003)->first();
    foreach(['rate'=>4,'updated_at'=>'2020-01-03 00:00:00','order_id'=>2,'user_id'=>21] as $field=>$changed){DB::table('reviews')->where('id',91003)->update([$field=>$changed]);$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[1]),409,'changed Review '.$field.' conflicts before deletion or a server receipt');DB::table('reviews')->where('id',91003)->update([$field=>$original[$field]]);}
    DB::table('orders')->where('id',1)->update(['user_id'=>21]);$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[1]),409,'a changed actual Review parent relationship conflicts before deletion');DB::table('orders')->where('id',1)->update(['user_id'=>20]);
    $freshScope=app(DesktopDashboardDevices::class)->device($link['token']);
    $branchActor=\App\Models\User::withoutGlobalScopes()->findOrFail(10);
    $foreign=new PDO('mysql:host=127.0.0.1;port='.config('database.connections.mysql.port').';dbname='.$database.';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
    DB::beginTransaction();
    try{
        DB::table('resturants')->where('id',100)->first();
        $foreign->exec('UPDATE resturants SET user_id=11 WHERE id=100');
        $reject(fn()=>app(DesktopDashboardReviewDeletion::class)->authorize($operations[0]['payload'],$branchActor,$freshScope),403,'a current locking branch read rejects ownership transferred after an older RR snapshot');
    }finally{DB::rollBack();$foreign->exec('UPDATE resturants SET user_id=10 WHERE id=100');}
    DB::table('reviews')->where('id',91003)->delete();$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[1]),409,'an independently deleted server Review becomes a narrow409 review conflict instead of an endless404 retry');DB::table('reviews')->insert($original);
    verify(!DB::table('desktop_dashboard_commands')->where('command_id',$operations[1]['command_id'])->exists()&&DB::table('reviews')->where('id',91003)->exists(),'every Review before-state conflict leaves no server receipt and retains the original row');
    $mapped=$operations[2];$dependency=(string)Str::uuid();$remote=92004;$row=(array)DB::table('reviews')->where('id',91004)->first();$row['id']=$remote;DB::table('reviews')->insert($row);DB::table('reviews')->where('id',91004)->update(['resturant_id'=>101,'order_id'=>2,'user_id'=>21]);
    DB::table('desktop_dashboard_commands')->insert(['device_id'=>$ownerDevice,'command_id'=>$dependency,'actor_id'=>1,'route_name'=>'review-fixture.source','request_hash'=>str_repeat('1',64),'command_cipher'=>Crypt::encryptString('{}'),'local_result_cipher'=>Crypt::encryptString('{}'),'server_result_cipher'=>Crypt::encryptString(json_encode(['references'=>[['entity'=>'resturant_review','local_id'=>91004,'server_id'=>$remote]]])),'dependencies'=>'[]','status'=>'acknowledged','attempts'=>0,'created_at'=>now(),'updated_at'=>now()]);
    $ref=['$desktop_ref'=>['entity'=>'resturant_review','command_id'=>$dependency,'local_id'=>91004]];$mapped['payload']['parameters']['review']=$ref;$mapped['payload']['facts']['review_before']['row']['id']=$ref;$mapped['dependencies']=[$dependency];
    $wrong=$mapped;$wrong['payload']['parameters']['review']['$desktop_ref']['entity']='review_order';$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$wrong),422,'a Review ID rejects a wrong typed entity before reference resolution');
    app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$mapped);verify(!DB::table('reviews')->where('id',$remote)->exists()&&DB::table('reviews')->where('id',91004)->value('resturant_id')==101,'an incoming typed Review reference deletes its mapped identity and preserves a colliding numeric Review');
    foreach([$operations[0],$operations[1],$mapped] as $operation){$reply=app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operation);$switch($ownerStage,true);app(DesktopDashboardJournal::class)->acknowledge($ownerDevice,$operation['command_id'],$reply);$switch($database);}
})();
