<?php
use Illuminate\Support\Facades\{DB,Crypt};
use Illuminate\Support\Str;
use App\Services\Dashboard\{DesktopDashboardBootstrap,DesktopDashboardDevices,DesktopDashboardJournal,DesktopDashboardReconciliation,DesktopDashboardWishlistDeletion};

// A closure keeps fixture variables out of the original shared HTTP origin/session scope.
(function() use($database,$ownerStage,$stage,$ownerDevice,$ownerLink,$remoteDevice,$link,$env,$application,$httpPort,$http,$profile,$pdo,$origin){
    $firstCheck=$GLOBALS['count'];
    $seed=function(int $id,int $restaurant=100,int $user=20){DB::table('wishlists')->insert(['id'=>$id,'resturant_id'=>$restaurant,'user_id'=>$user,'created_at'=>'2020-01-01 00:00:00','updated_at'=>'2020-01-02 00:00:00']);};
    $switch=function(string $db,bool $local=false){config(['database.connections.mysql.database'=>$db,'desktop_dashboard.local'=>$local]);DB::purge();};
    $command=function(string $uuid)use($ownerDevice){$row=DB::table('desktop_dashboard_commands')->where('command_id',$uuid)->first();$result=json_decode(Crypt::decryptString($row->local_result_cipher),true);return ['command_id'=>$uuid,'actor_id'=>1,'route_name'=>$row->route_name,'payload'=>json_decode(Crypt::decryptString($row->command_cipher),true),'local_result'=>$result['result'],'local_references'=>$result['references'],'dependencies'=>json_decode($row->dependencies,true),'occurred_at'=>\Carbon\Carbon::parse($row->created_at,'UTC')->toIso8601String()];};
    $reject=function(callable $work,int $status,string $message){try{$work();throw new RuntimeException('Wishlist operation unexpectedly succeeded.');}catch(\Symfony\Component\HttpKernel\Exception\HttpException $error){verify($error->getStatusCode()===$status,$message);}};
    $switch($database);$seed(91001);$seed(91002,101,21);
    $scoped=app(DesktopDashboardBootstrap::class)->export(app(DesktopDashboardDevices::class)->device($link['token']));
    verify(array_column($scoped['tables']['wishlists']['rows'],'id')===[91001]&&$scoped['coverage']['full_dashboard']===false,'Wishlist bootstrap includes only the enrolled F restaurant and keeps full dashboard coverage false');
    $switch($ownerStage,true);$seed(91001);$seed(91002,101,21);$seed(91003);$seed(91004);$seed(91005);
    DB::table('media')->insert(['id'=>95101,'model_type'=>\App\Models\Wishlist::class,'model_id'=>91001,'collection_name'=>'wishlist','name'=>'retained','file_name'=>'retained.txt','mime_type'=>'text/plain','disk'=>'public','conversions_disk'=>'public','size'=>18,'manipulations'=>'[]','custom_properties'=>'{}','generated_conversions'=>'{}','responsive_images'=>'{}']);
    $mediaFile=\Spatie\MediaLibrary\MediaCollections\Models\Media::findOrFail(95101)->getPath();mkdir(dirname($mediaFile),0700,true);file_put_contents($mediaFile,'retained-wishlist');$mediaHash=hash_file('sha256',$mediaFile);
    $preserved=['order'=>(array)DB::table('orders')->where('id',1)->first(),'user'=>(array)DB::table('users')->where('id',20)->first(),'restaurant'=>(array)DB::table('resturants')->where('id',100)->first(),'media'=>(array)DB::table('media')->where('id',95101)->first()];
    $localEnv=$env;$localEnv['DB_DATABASE']=$ownerStage;$localEnv['DESKTOP_DASHBOARD_LOCAL']='true';
    $web=proc_open([PHP_BINARY,'-S','127.0.0.1:'.$httpPort,'-t',$application.'/public',$application.'/desktop/router.php'],[['pipe','r'],['file',$profile.'/web.log','a'],['file',$profile.'/web.log','a']],$pipes,$application,$localEnv);
    $operations=[];
    try{
        for($n=0;$n<100;$n++){if($http('/_desktop/health')[0]===200)break;usleep(50000);}
        [$status,$page]=$http('/admin/notifications');preg_match('/name="csrf-token" content="([^"]+)"/',$page,$csrf);verify($status===200&&isset($csrf[1]),'the original local session supplies real Wishlist-delete CSRF');
        $form=['_token'=>$csrf[1],'_method'=>'DELETE','_desktop_command'=>(string)Str::uuid()];$before=DB::table('desktop_dashboard_commands')->count();
        [$status,$body,$headers]=$http('/admin/userWishlistsDelete/91001',$form,['Referer: '.$origin.'/admin/resturants/100']);
        verify($status===302&&in_array('Location: '.$origin.'/admin/resturants/100',$headers,true)&&!DB::table('wishlists')->where('id',91001)->exists()&&DB::table('desktop_dashboard_commands')->count()===$before+1,'the original Wishlist controller deletes exactly its row with one encrypted local command');
        verify($http('/admin/userWishlistsDelete/91001',$form)[0]===302&&DB::table('desktop_dashboard_commands')->count()===$before+1,'a lost local Wishlist-delete redirect replays after the Wishlist ID has disappeared');
        foreach($preserved as $kind=>$row){$table=['order'=>'orders','user'=>'users','restaurant'=>'resturants','media'=>'media'][$kind];verify((array)DB::table($table)->where('id',$row['id'])->first()===$row,'Wishlist deletion preserves the original '.$kind.' row, including balances/rating/media');}
        verify(is_file($mediaFile)&&hash_file('sha256',$mediaFile)===$mediaHash,'the original query-delete bypasses model media events and preserves its actual attached file');
        $saved=$command($form['_desktop_command']);verify(count($saved['payload']['facts']['wishlist_before']['row'])===5&&$saved['payload']['facts']['wishlist_before']['row']['updated_at']==='2020-01-02 00:00:00'&&$saved['local_result']['http']['status']===302,'the encrypted before-state includes all five Wishlist columns, actual user/restaurant identities and original redirect outcome');$operations[]=$saved;
        DB::table('users')->where('id',1)->update(['status'=>'disabled']);verify($http('/admin/userWishlistsDelete/91001',$form,['Accept: application/json'])[0]===403,'a disabled local actor cannot use a saved deleted-Wishlist reply');DB::table('users')->where('id',1)->update(['status'=>'accepted']);
        DB::table('users')->where('id',1)->update(['owner_resturant_id'=>101]);verify($http('/admin/userWishlistsDelete/91001',$form,['Accept: application/json'])[0]===403,'a saved local Wishlist reply checks the current enrolled restaurant relationship');DB::table('users')->where('id',1)->update(['owner_resturant_id'=>null]);
        DB::table('users')->where('id',1)->update(['app_scope'=>'go_admin']);verify($http('/admin/userWishlistsDelete/91001',$form)[0]===302,'an enrolled central GO administrator retains the original admin guard for an F Wishlist without invented app-scope or delete grants');DB::table('users')->where('id',1)->update(['app_scope'=>'fasakhansta']);
        $bad=$form;$bad['_desktop_command']=(string)Str::uuid();verify($http('/admin/userWishlistsDelete/999999',$bad,['Accept: application/json'])[0]===409,'an unknown local Wishlist cannot prove enrolled before-facts and creates no success command');
        verify($http('/admin/userWishlistsDelete/91003',$form,['X-Fasakhansta-Command: '.Str::uuid(),'Accept: application/json'])[0]===409&&DB::table('wishlists')->where('id',91003)->exists(),'conflicting immutable header and form UUIDs reject before the original delete');
        $bad=$form;$bad['_desktop_command']=[(string)Str::uuid()];$queued=DB::table('desktop_dashboard_commands')->count();verify($http('/admin/userWishlistsDelete/91003',$bad,['Accept: application/json'])[0]===422&&DB::table('wishlists')->where('id',91003)->exists()&&DB::table('desktop_dashboard_commands')->count()===$queued,'an array logical UUID receives real local422 without string conversion, deletion or a queued command');
        $bad=$form;$bad['_desktop_command']=(string)Str::uuid();$bad['rate']=1;verify($http('/admin/userWishlistsDelete/91003',$bad,['Accept: application/json'])[0]===422&&DB::table('wishlists')->where('id',91003)->exists(),'Wishlist deletion cannot silently accept an unrelated update field');
        foreach([91003,91004] as $id){$next=$form;$next['_desktop_command']=(string)Str::uuid();verify($http('/admin/userWishlistsDelete/'.$id,$next)[0]===302,'the original controller prepares an immutable Wishlist replay fixture');$operations[]=$command($next['_desktop_command']);}
        DB::unprepared("CREATE TRIGGER reject_wishlist_journal BEFORE INSERT ON desktop_dashboard_commands FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='fixture Wishlist journal failure'");
        try{$next=$form;$next['_desktop_command']=(string)Str::uuid();verify($http('/admin/userWishlistsDelete/91005',$next,['Accept: application/json'])[0]===500&&DB::table('wishlists')->where('id',91005)->exists(),'failure to save the local command rolls back the original Wishlist deletion');}finally{DB::unprepared('DROP TRIGGER reject_wishlist_journal');}
    }finally{fclose($pipes[0]);proc_terminate($web);proc_close($web);}
    $switch($database);$seed(91003);$seed(91004);
    $actor=\App\Models\User::withoutGlobalScopes()->findOrFail(1);verify(!$actor->getAllPermissions()->pluck('name')->intersect(['resturant-delete','user-delete'])->count(),'Wishlist replay uses the original custom IsAdmin guard without invented resource-delete permissions');
    $receipt=app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[0]);verify($receipt===app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[0])&&!DB::table('wishlists')->where('id',91001)->exists(),'Wishlist reconciliation invokes the original controller once and returns an identical lost-response receipt');
    DB::table('users')->where('id',1)->update(['owner_resturant_id'=>101]);$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[0]),403,'a stored server Wishlist receipt requires the current actor restaurant scope before deduplication');DB::table('users')->where('id',1)->update(['owner_resturant_id'=>null]);
    DB::table('desktop_dashboard_devices')->where('id',$remoteDevice->id)->update(['enabled'=>false]);$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[0]),401,'a revoked current device cannot obtain the saved Wishlist receipt');DB::table('desktop_dashboard_devices')->where('id',$remoteDevice->id)->update(['enabled'=>true]);
    $original=(array)DB::table('wishlists')->where('id',91003)->first();
    foreach(['created_at'=>'2020-01-03 00:00:00','updated_at'=>'2020-01-03 00:00:00','resturant_id'=>101,'user_id'=>21] as $field=>$changed){DB::table('wishlists')->where('id',91003)->update([$field=>$changed]);$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[1]),409,'changed Wishlist '.$field.' conflicts before deletion or a server receipt');DB::table('wishlists')->where('id',91003)->update([$field=>$original[$field]]);}
    DB::table('users')->where('id',20)->update(['app_scope'=>'go_partner']);$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[1]),409,'a changed actual Wishlist user identity conflicts before deletion');DB::table('users')->where('id',20)->update(['app_scope'=>'fasakhansta']);
    DB::table('resturants')->where('id',100)->update(['user_id'=>11]);$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[1]),409,'a changed actual Wishlist restaurant ownership conflicts before deletion');DB::table('resturants')->where('id',100)->update(['user_id'=>10]);
    $freshScope=app(DesktopDashboardDevices::class)->device($link['token']);
    $branchActor=\App\Models\User::withoutGlobalScopes()->findOrFail(10);
    $foreign=new PDO('mysql:host=127.0.0.1;port='.config('database.connections.mysql.port').';dbname='.$database.';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
    DB::beginTransaction();
    try{
        DB::table('resturants')->where('id',100)->first();
        $foreign->exec('UPDATE resturants SET user_id=11 WHERE id=100');
        $reject(fn()=>app(DesktopDashboardWishlistDeletion::class)->authorize($operations[0]['payload'],$branchActor,$freshScope),403,'a current locking branch read rejects ownership transferred after an older RR snapshot');
    }finally{DB::rollBack();$foreign->exec('UPDATE resturants SET user_id=10 WHERE id=100');}
    DB::table('wishlists')->where('id',91003)->delete();$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operations[1]),409,'an independently deleted server Wishlist becomes a narrow409 wishlist conflict instead of an endless404 retry');DB::table('wishlists')->insert($original);
    verify(!DB::table('desktop_dashboard_commands')->where('command_id',$operations[1]['command_id'])->exists()&&DB::table('wishlists')->where('id',91003)->exists(),'every Wishlist before-state conflict leaves no server receipt and retains the original row');
    $mapped=$operations[2];$dependency=(string)Str::uuid();$remote=92004;$row=(array)DB::table('wishlists')->where('id',91004)->first();$row['id']=$remote;DB::table('wishlists')->insert($row);DB::table('wishlists')->where('id',91004)->update(['resturant_id'=>101,'user_id'=>21]);
    DB::table('desktop_dashboard_commands')->insert(['device_id'=>$ownerDevice,'command_id'=>$dependency,'actor_id'=>1,'route_name'=>'wishlist-fixture.source','request_hash'=>str_repeat('1',64),'command_cipher'=>Crypt::encryptString('{}'),'local_result_cipher'=>Crypt::encryptString('{}'),'server_result_cipher'=>Crypt::encryptString(json_encode(['references'=>[['entity'=>'user_wishlist','local_id'=>91004,'server_id'=>$remote]]])),'dependencies'=>'[]','status'=>'acknowledged','attempts'=>0,'created_at'=>now(),'updated_at'=>now()]);
    $ref=['$desktop_ref'=>['entity'=>'user_wishlist','command_id'=>$dependency,'local_id'=>91004]];$mapped['payload']['parameters']['id']=$ref;$mapped['payload']['facts']['wishlist_before']['row']['id']=$ref;$mapped['dependencies']=[$dependency];
    $wrong=$mapped;$wrong['payload']['parameters']['id']['$desktop_ref']['entity']='wishlist_user';$reject(fn()=>app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$wrong),422,'a Wishlist ID rejects a wrong typed entity before reference resolution');
    app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$mapped);verify(!DB::table('wishlists')->where('id',$remote)->exists()&&DB::table('wishlists')->where('id',91004)->value('resturant_id')==101,'an incoming typed Wishlist reference deletes its mapped identity and preserves a colliding numeric Wishlist');
    foreach([$operations[0],$operations[1],$mapped] as $operation){$reply=app(DesktopDashboardReconciliation::class)->ingest($remoteDevice,$operation);$switch($ownerStage,true);app(DesktopDashboardJournal::class)->acknowledge($ownerDevice,$operation['command_id'],$reply);$switch($database);}
    echo 'WISHLIST_LOCAL_RECONCILIATION_COMPLETE '.json_encode(['checks'=>$GLOBALS['count']-$firstCheck,'fullBeforeColumns'=>5,'mediaRetained'=>true,'typedReferences'=>true,'fullDashboard'=>false]).PHP_EOL;
})();
