const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'), os=require('node:os'), path=require('node:path');
const Store=require('../src/store.cjs'),Sync=require('../src/sync.cjs'),D=require('../src/domain.js'),receipt=require('../src/receipt.cjs');
const {randomUUID}=require('node:crypto');
const snapshot=(price=10000)=>({id:randomUUID(),generated_at:new Date().toISOString(),branch:{value:'f:100',name:'فرع اختبار'},actor:{id:10,name:'كاشير'},tax_bps:1400,service_bps:1000,can_discount:false,categories:[],products:[{id:1,name:'رنجة',unit:'kg',variants:[{option_id:'',label:'أساسي',unit_price_cents:price,quantity_mode:'weight',inventory:{}}]}]});
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'fasakhansta-pos-')),file=path.join(dir,'pos.sqlite'),s=new Store(file);s.saveSnapshot(snapshot());t.after(()=>{try{s.close();}catch{}fs.rmSync(dir,{recursive:true,force:true});});return {s,file};}
function data(o,extra={}){return {...o.data,items:[{product_id:1,option_id:'',quantity_mode:'weight',quantity:'0.250'}],cash_received:'100.00',...extra};}
test('integer rounding, merged fractions, tax, service and phone delivery agree with POS rules',()=>{
 const snap=snapshot(9999);const d=data({data:{channel:'dine'}},{customer_name:'عميل',table_name:'١'});d.items.push({...d.items[0]});
 const q=D.quote(snap,d);assert.equal(q.subtotal_cents,5000);assert.equal(q.service_cents,500);assert.equal(q.tax_cents,770);assert.equal(q.total_cents,6270);
 assert.equal(D.quote(snap,{...d,channel:'phone',delivery_cents:2000}).total_cents,7980);
});
test('drafts persist after closing and reopening the process without network',t=>{const {s,file}=fixture(t),o=s.newOrder();s.update(o.id,data(o));s.close();const reopened=new Store(file);assert.equal(reopened.order(o.id).data.items[0].quantity,'0.250');reopened.close();});
test('sale and outbox commit together; a simulated storage failure rolls both back',t=>{const {s}=fixture(t),o=s.newOrder();s.update(o.id,data(o));s.db.exec("CREATE TRIGGER storage_failure BEFORE INSERT ON outbox BEGIN SELECT RAISE(ABORT,'disk full'); END;");assert.throws(()=>s.dispatch(o.id,'sale'),/disk full/);assert.equal(s.order(o.id).status,'draft');assert.equal(s.order(o.id).revision,0);assert.equal(s.pending().length,0);});
test('committed sale survives restart before printing or uploading',t=>{const {s,file}=fixture(t),o=s.newOrder();s.update(o.id,data(o));const e=s.dispatch(o.id,'sale');s.close();const reopened=new Store(file);assert.equal(reopened.order(o.id).status,'paid');assert.equal(reopened.pending()[0].event.id,e.id);reopened.close();});
test('lost server response retries the same UUID exactly once, also after restart',async t=>{const {s}=fixture(t),o=s.newOrder();s.update(o.id,data(o));const e=s.dispatch(o.id,'sale'),committed=new Map();let lost=true,collections=0;
 const request=async(method,endpoint,body)=>{if(endpoint==='sync'){const id=body.event.id;if(!committed.has(id)){collections++;committed.set(id,{id});}if(lost){lost=false;throw Error('response lost');}return committed.get(id);}if(endpoint==='snapshot')return s.snapshot();return {ok:true};};
 const sync=new Sync(s,request);await sync.run();assert.equal(s.pending()[0].id,e.id);await sync.run();assert.equal(s.counts().pending,0);assert.equal(collections,1);
});
test('a conflicting first operation remains queued and later revisions are not sent',async t=>{const {s}=fixture(t),o=s.newOrder();s.update(o.id,data(o));const first=s.dispatch(o.id,'kitchen');s.dispatch(o.id,'bill');let calls=0;
 const sync=new Sync(s,async()=>{calls++;const e=Error('conflict');e.status=409;throw e;});await sync.run();assert.equal(calls,1);assert.equal(s.pending().length,2);assert.equal(s.pending()[0].id,first.id);assert.match(s.pending()[0].last_error,/conflict/);
});
test('receipt printing and reprinting never create another sale or outbox record',t=>{const {s}=fixture(t),o=s.newOrder();s.update(o.id,data(o));const e=s.dispatch(o.id,'sale');s.markPrinted(e.id);s.markPrinted(e.id);assert.equal(s.history().length,1);assert.equal(s.history()[0].printed,2);assert.equal(s.order(o.id).revision,1);});
test('menu refresh preserves the price snapshot of an already opened invoice',t=>{const {s}=fixture(t),o=s.newOrder();s.update(o.id,data(o));s.saveSnapshot(snapshot(30000));const a=s.order(o.id);assert.equal(D.quote(a.snapshot,a.data).subtotal_cents,2500);const b=s.newOrder();s.update(b.id,data(b));assert.equal(D.quote(s.order(b.id).snapshot,s.order(b.id).data).subtotal_cents,7500);});
test('bill issuance locks contents and permits cash_received only',t=>{const {s}=fixture(t),o=s.newOrder();s.update(o.id,data(o));s.dispatch(o.id,'bill');const bill=s.order(o.id);assert.throws(()=>s.update(o.id,{...bill.data,notes:'modified'}),/ثابتة/);s.update(o.id,{...bill.data,cash_received:'200.00'});assert.equal(s.dispatch(o.id,'sale').kind,'sale');});
test('underpayment, fractional pieces and cancellation after kitchen are rejected',t=>{const {s}=fixture(t),o=s.newOrder();s.update(o.id,data(o,{cash_received:'0'}));assert.throws(()=>s.dispatch(o.id,'sale'),/أقل/);s.dispatch(o.id,'kitchen');assert.throws(()=>s.dispatch(o.id,'cancel','سبب'),/إلغاء/);assert.throws(()=>D.quote(snapshot(),data(o,{items:[{product_id:1,option_id:'',quantity_mode:'piece',quantity:'0.250'}]})));});
test('unknown server acknowledgement cannot remove a pending operation',t=>{const {s}=fixture(t),o=s.newOrder();s.update(o.id,data(o));const e=s.dispatch(o.id,'sale');assert.throws(()=>s.acknowledge(e.id,{id:randomUUID()}));assert.equal(s.counts().pending,1);});
test('customer fields and product names cannot inject receipt HTML',()=>{const snap=snapshot();snap.products[0].name='<script>attack()</script>';const html=receipt({kind:'sale',id:randomUUID(),order_id:randomUUID(),occurred_at:new Date().toISOString(),data:data({data:{channel:'takeaway'}},{customer_name:'<img src=x onerror=attack()>'})},snap);assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<img '));assert.ok(html.includes('&lt;script&gt;'));});
test('discount permission, invalid numbers and maximum totals are enforced',()=>{const snap=snapshot();assert.throws(()=>D.quote(snap,data({data:{channel:'takeaway'}},{discount:'1',discount_reason:'خصم'})));assert.equal(D.decimal('١٢٫٥٠'),1250);assert.throws(()=>D.decimal('NaN'));assert.throws(()=>D.quote(snapshot(100000000),data({data:{channel:'takeaway'}},{items:[{product_id:1,option_id:'',quantity_mode:'weight',quantity:'1000'}]})));});
test('unused empty drafts can be discarded without deleting a persisted sale',t=>{const {s}=fixture(t),empty=s.newOrder();s.discard(empty.id);assert.equal(s.openOrders().length,0);const o=s.newOrder();s.update(o.id,data(o));assert.throws(()=>s.discard(o.id));s.dispatch(o.id,'sale');assert.throws(()=>s.discard(o.id));assert.equal(s.pending().length,1);});
test('a known revoked device blocks new writes while retaining every pending operation',async t=>{const {s}=fixture(t),o=s.newOrder();s.update(o.id,data(o));s.dispatch(o.id,'sale');const sync=new Sync(s,async()=>{const e=Error('revoked');e.status=401;throw e;});await sync.run();assert.equal(s.get('authorization_blocked'),true);assert.equal(s.pending().length,1);assert.equal(sync.online,false);});
test('a missing or zero catalog price cannot create a zero-price sale or outbox event',t=>{const {s}=fixture(t);s.saveSnapshot(snapshot(0));const o=s.newOrder();assert.throws(()=>s.update(o.id,data(o)),/سعر الصنف غير محدد/);assert.equal(s.pending().length,0);assert.equal(s.order(o.id).data.items.length,0);});
