@extends('erp.layout')
@section('title','الحسابات والكاش')
@section('subtitle','دفتر قيود متوازن وحركة الخزينة المركزية')
@section('heading-action')<button type="button" class="secondary" data-print>طباعة ميزان المراجعة</button>@endsection
@section('content')
@if(!$state->initialized_at)
<section class="card"><h2>تهيئة الأرصدة الافتتاحية</h2><p>قيمة المخزون الحالية: <strong>{{ \App\Services\Erp\Decimal::format($openingStock) }} ج.م</strong> • صافي كشوف المرتبات المعتمدة: <strong>{{ \App\Services\Erp\Decimal::format($openingPayroll) }} ج.م</strong></p>
<p class="note">ستُرحّل هذه الأرصدة كبداية للدفتر، ويُعتبر كل كشف مرتب معتمد سابقًا غير مصروف. راجع ذلك قبل التهيئة. لا تُستورد مبيعات التطبيق أو أرصدة بنوك أو موردين من خارج ERP تلقائيًا.</p>
@if($actor->can('access.manage'))<form method="post" action="{{ route('erp.finance.initialize') }}" data-confirm="هل راجعت المخزون والمرتبات غير المصروفة والكاش الفعلي؟ التهيئة تتم مرة واحدة.">@csrf<div class="field"><label>النقد الفعلي في الخزينة المركزية بالجنيه<input name="cash" type="number" min="0" step="0.01" value="0" required></label></div><label class="check"><input name="confirmed" type="checkbox" value="1" required>راجعت الأرصدة وأؤكد أن كشوف المرتبات السابقة غير مصروفة</label><div class="actions"><button>تهيئة الدفتر</button></div></form>@else<div class="notice">التهيئة متاحة للمالك فقط.</div>@endif
</section>
@else
<div class="cards"><div class="card stat"><div class="stat-label">الخزينة المركزية</div><div class="stat-value">{{ \App\Services\Erp\Decimal::format($cash) }}</div><small>جنيه مصري</small></div><div class="card stat"><div class="stat-label">مستحقات الموردين</div><div class="stat-value">{{ \App\Services\Erp\Decimal::format($supplierOwed) }}</div><small>من المشتريات المسجلة</small></div><div class="card stat"><div class="stat-label">مرتبات غير مصروفة</div><div class="stat-value">{{ \App\Services\Erp\Decimal::format($payrollOwed) }}</div><small>كشوف معتمدة</small></div></div>
<details class="card"><summary><strong>تسجيل حركة كاش</strong></summary><div class="details-body"><form method="post" action="{{ route('erp.finance.cash') }}" data-cash-form data-confirm="هل تؤكد أن حركة النقد تمت فعليًا وبالقيمة الموضحة؟">@csrf<input type="hidden" name="request_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><div class="fields">
<div class="field"><label>نوع الحركة<select name="type"><option value="funding">تمويل نقدي من المالك</option><option value="expense">مصروف تشغيلي</option><option value="supplier_payment">سداد مورد</option>@if($actor->can('payroll.manage'))<option value="payroll_payment">صرف مرتب معتمد</option>@endif</select></label></div>
<div class="field"><label>المبلغ بالجنيه<input name="amount" type="number" min="0.01" step="0.01" required></label></div>
<div class="field"><label>المورد — للسداد فقط<select name="supplier_id"><option value="">اختر المورد</option>@foreach($suppliers as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select></label></div>
<div class="field"><label>الفرع المستفيد — للمصروف فقط<select name="branch_id"><option value="">الإدارة المركزية</option>@foreach($branches as $b)<option value="{{ $b->id }}">{{ $b->name }}</option>@endforeach</select></label></div>
@if($actor->can('payroll.manage'))<div class="field full"><label>كشف المرتب — للصرف فقط<select name="payroll_id"><option value="">اختر كشفًا غير مصروف</option>@foreach($unpaid as $p)<option value="{{ $p->id }}">#{{ $p->id }} — {{ $p->employee_name }} — {{ $p->month }} — {{ \App\Services\Erp\Decimal::format($p->net_minor) }} ج.م</option>@endforeach</select></label></div>@endif
<div class="field full"><label>سبب الحركة ومرجع سند الصرف أو الإيداع<textarea name="reason" required maxlength="500"></textarea></label></div></div><p class="note">السداد يُخصم من رصيد المورد، وصرف المرتب يجب أن يساوي صافي الكشف كاملًا. التسجيل يوثق النقد؛ لا ينفذ تحويلًا بنكيًا أو دفعًا إلكترونيًا.</p><div class="actions"><button>ترحيل حركة الكاش</button></div></form></div></details>
@endif
<section class="card"><h2>ميزان المراجعة — منذ بداية الدفتر</h2><p class="note">الأرصدة تخص العمليات المسجلة في ERP. هذا ليس تقرير صافي ربح شامل؛ مبيعات التطبيق والضرائب والتكاليف غير المسجلة غير مدرجة. الاستلامات المباشرة واستقطاعات السلف تظهر بحسابات تسوية تحتاج مراجعة.</p>
<div class="table-wrap"><table><thead><tr><th>الحساب</th><th>إجمالي مدين</th><th>إجمالي دائن</th><th>رصيد مدين</th><th>رصيد دائن</th></tr></thead><tbody>
@foreach($accounts as $account)@php($row=$balances[$account->code]??null)@php($debit=(int)optional($row)->debit)@php($credit=(int)optional($row)->credit)<tr><td>{{ $account->name }}</td><td>{{ \App\Services\Erp\Decimal::format($debit) }}</td><td>{{ \App\Services\Erp\Decimal::format($credit) }}</td><td>{{ \App\Services\Erp\Decimal::format(max(0,$debit-$credit)) }}</td><td>{{ \App\Services\Erp\Decimal::format(max(0,$credit-$debit)) }}</td></tr>@endforeach
<tr><th>إجمالي الحركة</th><th>{{ \App\Services\Erp\Decimal::format((int)$balances->sum('debit')) }}</th><th>{{ \App\Services\Erp\Decimal::format((int)$balances->sum('credit')) }}</th><th colspan="2">{{ (int)$balances->sum('debit')===(int)$balances->sum('credit') ? 'متوازن':'يحتاج مراجعة' }}</th></tr>
</tbody></table></div></section>
<section class="card"><h2>القيود المحاسبية</h2>@forelse($journals as $journal)<details class="details"><summary><strong>#{{ $journal->id }} — {{ $journal->description }}</strong> <span class="badge">{{ $journal->entry_date }}</span></summary><div class="details-body table-wrap"><table><thead><tr><th>الحساب</th><th>مدين</th><th>دائن</th></tr></thead><tbody>@foreach($journalLines[$journal->id]??[] as $line)<tr><td>{{ $line->account_name }}</td><td>{{ \App\Services\Erp\Decimal::format($line->debit_minor) }}</td><td>{{ \App\Services\Erp\Decimal::format($line->credit_minor) }}</td></tr>@endforeach</tbody></table></div></details>@empty<div class="empty">لا توجد قيود مرحّلة.</div>@endforelse @include('erp.pagination',['paginator'=>$journals])</section>
@endsection
