@extends('erp.layout')
@section('title','المخزون والحركات')
@section('subtitle','أرصدة فعلية وحركات موثقة لكل مخزن')
@section('content')
@php($types = ['opening'=>'رصيد افتتاحي','receipt'=>'استلام بضاعة','transfer'=>'تحويل واستلام مباشر','waste'=>'هالك','count'=>'تسوية جرد','purchase'=>'استلام مشتريات','production_out'=>'صرف تصنيع','production_in'=>'ناتج تصنيع'])
@include('erp.filter')
<section class="card"><div class="section-header"><h2>أرصدة المخازن</h2><span class="badge">{{ $balances->total() }} رصيد</span></div><div class="table-wrap"><table><thead><tr><th>الصنف</th><th>المخزن</th><th>المتاح</th><th>حد التنبيه</th><th>القيمة الدفترية</th><th>الحالة</th></tr></thead><tbody>
@forelse($balances as $b)<tr><td><strong>{{ $b->item_name }}</strong></td><td>{{ $b->warehouse_name }}</td><td class="number">{{ \App\Services\Erp\Decimal::format($b->quantity_milli,3) }} {{ $b->unit === 'kg' ? 'كجم' : 'قطعة' }}</td><td class="number">{{ \App\Services\Erp\Decimal::format($b->minimum_milli,3) }}</td><td class="number">{{ \App\Services\Erp\Decimal::format($b->value_minor) }} ج.م</td><td><span class="badge {{ $b->quantity_milli <= $b->minimum_milli ? 'red':'green' }}">{{ $b->quantity_milli <= $b->minimum_milli ? 'يحتاج توريد':'متاح' }}</span></td></tr>@empty<tr><td colspan="6" class="empty">ابدأ بإضافة صنف وتسجيل رصيده الافتتاحي في المخزن.</td></tr>@endforelse
</tbody></table></div>@include('erp.pagination',['paginator'=>$balances])<p class="note">الأرصدة تخص الأصناف التي سُجلت لها حركات. خصم خامات طلبات التطبيق تلقائيًا يحتاج ربط الوصفات في مرحلة التصنيع.</p></section>
<section class="card"><h2>تسجيل حركة مخزون</h2><form method="post" action="{{ route('erp.stock.post') }}" data-stock-form data-confirm="هل تؤكد ترحيل هذه الحركة؟ التحويل يثبت خروج البضاعة واستلامها فورًا.">@csrf<input type="hidden" name="request_key" value="{{ old('request_key', (string) \Illuminate\Support\Str::uuid()) }}"><div class="fields">
<div class="field"><label>نوع الحركة<select name="type" required>@foreach(array_intersect_key($types,array_flip(['opening','receipt','transfer','waste','count'])) as $value=>$label)<option value="{{ $value }}" {{ old('type') === $value ? 'selected':'' }}>{{ $label }}</option>@endforeach</select></label></div>
<div class="field"><label>الصنف<select name="item_id" required><option value="">اختر الصنف</option>@foreach($items as $item)<option value="{{ $item->id }}" {{ (int)old('item_id') === (int)$item->id ? 'selected':'' }}>{{ $item->sku }} — {{ $item->name }} ({{ $item->unit === 'kg' ? 'كجم':'قطعة' }})</option>@endforeach</select></label></div>
<div class="field"><label>المخزن / مخزن الإرسال<select name="warehouse_id" required><option value="">اختر المخزن</option>@foreach($warehouses as $w)<option value="{{ $w->id }}" {{ (int)old('warehouse_id') === (int)$w->id ? 'selected':'' }}>{{ $w->name }}</option>@endforeach</select></label></div>
<div class="field"><label>مخزن الاستلام — للتحويل فقط<select name="destination_id"><option value="">اختر عند التحويل</option>@foreach($warehouses as $w)<option value="{{ $w->id }}" {{ (int)old('destination_id') === (int)$w->id ? 'selected':'' }}>{{ $w->name }}</option>@endforeach</select></label></div>
<div class="field"><label>الكمية — أو العدد الفعلي عند الجرد<input name="quantity" type="number" min="0" step="0.001" required value="{{ old('quantity') }}"></label></div>
<div class="field"><label>تكلفة الوحدة الواردة بالجنيه<input name="unit_cost" type="number" min="0" step="0.01" value="{{ old('unit_cost') }}" placeholder="للافتتاحي والاستلام وزيادة الجرد"></label></div>
<div class="field"><label>الرصيد الدفتري قبل الجرد<input name="expected_quantity" type="number" min="0" step="0.001" value="{{ old('expected_quantity') }}" placeholder="للجرد فقط: انسخ الرصيد الظاهر أعلاه"></label></div>
<div class="field"><label>مرجع الفاتورة أو المستند<input name="reference" maxlength="160" value="{{ old('reference') }}"></label></div>
<div class="field full"><label>سبب الحركة / ملاحظات الاستلام<textarea name="reason" required maxlength="500">{{ old('reason') }}</textarea></label></div></div><p class="note">التحويل المباشر يُستخدم بعد تأكيد الاستلام الفعلي. التحويل والهالك يُقيّمان بمتوسط التكلفة. القطع تُسجل بأعداد صحيحة. لعرض مخازن فروع مختلفة اختر «جميع الفروع».</p><div class="actions"><button {{ $items->isEmpty() || $warehouses->isEmpty() ? 'disabled':'' }}>ترحيل الحركة</button></div></form></section>
@if($actor->allBranches())<details class="card"><summary><strong>إضافة صنف مخزني</strong></summary><form class="details-body" method="post" action="{{ route('erp.items.save') }}">@csrf<div class="fields"><div class="field"><label>كود الصنف<input name="sku" required maxlength="64" placeholder="RAW-001"></label></div><div class="field"><label>اسم الصنف<input name="name" required maxlength="160"></label></div><div class="field"><label>التصنيف<select name="category"><option value="raw">خامات</option><option value="finished">منتج جاهز</option><option value="packaging">تغليف</option></select></label></div><div class="field"><label>الوحدة<select name="unit"><option value="kg">كيلوجرام</option><option value="piece">قطعة</option></select></label></div><div class="field"><label>حد تنبيه نقص المخزون<input name="minimum" type="number" min="0" step="0.001" value="0" required></label></div></div><div class="actions"><button>إضافة الصنف</button></div></form></details>@endif
<section class="card"><h2>آخر الحركات</h2><div class="table-wrap"><table><thead><tr><th>المستند / التاريخ</th><th>الحركة</th><th>الصنف</th><th>المخازن</th><th>الكمية</th><th>القيمة</th><th>السبب والمرجع</th></tr></thead><tbody>@forelse($documents as $d)<tr><td>#{{ $d->id }}<br><small>{{ \Carbon\Carbon::parse($d->created_at)->timezone(config('erp.timezone'))->format('Y-m-d H:i') }}</small></td><td>{{ $types[$d->type] ?? $d->type }}</td><td>{{ $d->item_name }}</td><td>{{ $d->warehouse_name }}@if($d->destination_name)<br>إلى {{ $d->destination_name }}@endif</td><td class="number">{{ \App\Services\Erp\Decimal::format($d->quantity_milli,3) }}</td><td class="number">{{ \App\Services\Erp\Decimal::format($d->value_minor) }}</td><td>{{ $d->reason }}<br><small>{{ $d->reference }}</small></td></tr>@empty<tr><td colspan="7" class="empty">لم تُسجل حركات بعد.</td></tr>@endforelse</tbody></table></div>@include('erp.pagination',['paginator'=>$documents])</section>
@endsection
