@extends('erp.layout')
@section('title','كشوف المرتبات')
@section('subtitle','استحقاقات شهرية ومكافآت وخصومات مع اعتماد ثابت لكل كشف')
@section('heading-action')<button class="secondary" type="button" data-print>طباعة الكشوف</button>@endsection
@section('content')
@php($adjustmentNames = ['bonus'=>'مكافأة','deduction'=>'خصم','advance_repayment'=>'استقطاع سلفة'])
@include('erp.filter')
<div class="notice">الكشف يحسب الراتب الشهري المسجل والتسويات اليدوية. أيام الحضور لا تخصم تلقائيًا، ولا تُحسب تجزئة شهر التعيين تلقائيًا. اعتماد الكشف يثبت الاستحقاق ولا يسجل صرفًا نقديًا أو سلفة جديدة.</div>
<section class="card"><h2>استحقاقات {{ $month }}</h2><div class="table-wrap"><table><thead><tr><th>الموظف</th><th>الأساسي</th><th>المكافآت</th><th>الخصومات</th><th>استقطاع السلف</th><th>الصافي</th><th>الحالة</th></tr></thead><tbody>@forelse($employees as $e)@php($s = $statements[$e->id])<tr><td><strong>{{ $e->name }}</strong><br><small>{{ optional($branches->firstWhere('id',$e->branch_id))->name }}{{ !$e->active ? ' • غير نشط':'' }}</small></td>@foreach(['base_minor','bonus_minor','deduction_minor','advance_minor','net_minor'] as $key)<td class="number">{{ \App\Services\Erp\Decimal::format($s[$key]) }}</td>@endforeach<td><span class="badge {{ $s['closed'] ? 'green':'' }}">{{ $s['closed'] ? 'معتمد':'مسودة' }}</span></td></tr>@empty<tr><td colspan="7" class="empty">لا يوجد موظفون لهذا الشهر والفرع.</td></tr>@endforelse</tbody></table></div>@include('erp.pagination',['paginator'=>$employees])</section>
@foreach($employees as $e)@php($s = $statements[$e->id])<details class="card payroll-detail"><summary><strong>{{ $e->name }}</strong> — {{ $s['closed'] ? 'كشف معتمد':'تسويات واعتماد الكشف' }}</summary><div class="details-body">
@if(!$s['closed'])<div class="grid2"><form method="post" action="{{ route('erp.salary',$e->id) }}">@csrf<h3>الراتب وتاريخ سريانه</h3><div class="fields"><div class="field"><label>ساري من شهر<input type="month" name="month" value="{{ $month }}" required></label></div><div class="field"><label>الراتب الأساسي بالجنيه<input type="number" name="salary" step="0.01" min="0" value="{{ \App\Services\Erp\Decimal::format($s['base_minor']) }}" required></label></div></div><div class="actions"><button class="secondary small">حفظ الراتب</button></div></form><form method="post" action="{{ route('erp.adjustment',$e->id) }}">@csrf<input type="hidden" name="request_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><input type="hidden" name="month" value="{{ $month }}"><h3>إضافة تسوية</h3><div class="fields"><div class="field"><label>النوع<select name="type">@foreach($adjustmentNames as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label></div><div class="field"><label>القيمة بالجنيه<input type="number" name="amount" min="0.01" step="0.01" required></label></div><div class="field full"><label>السبب<input name="reason" required maxlength="500"></label></div></div><div class="actions"><button class="secondary small">تسجيل التسوية</button></div></form></div>@endif
<div class="table-wrap"><table><thead><tr><th>التسوية</th><th>القيمة</th><th>السبب</th></tr></thead><tbody>@forelse($adjustments->where('employee_id',$e->id) as $a)<tr><td>{{ $adjustmentNames[$a->type] }}</td><td>{{ \App\Services\Erp\Decimal::format($a->amount_minor) }}</td><td>{{ $a->reason }}</td></tr>@empty<tr><td colspan="3" class="empty">لا توجد تسويات مسجلة.</td></tr>@endforelse</tbody></table></div>
@if(!$s['closed'])<form class="actions" method="post" action="{{ route('erp.payroll.close',$e->id) }}" data-confirm="اعتماد الكشف سيقفل الراتب والتسويات والحضور لهذا الشهر. هل راجعت البيانات؟">@csrf<input type="hidden" name="month" value="{{ $month }}"><button>اعتماد كشف {{ $month }}</button></form>@else<p class="note">تم تثبيت هذا الكشف. لا يمكن تغيير حضوره أو تسوياته أو راتبه بأثر رجعي.</p>@endif</div></details>@endforeach
@endsection
