@extends('admin.index')
@push('custom-css')
<link rel="stylesheet" href="{{ asset('dashboard/css/phone-orders.css') }}?v={{ filemtime(public_path('dashboard/css/phone-orders.css')) }}">
@endpush
@section('content')
<div class="content-wrapper phone-orders-wrapper">
<main id="phone-orders" class="ph-pos ph-step-number" aria-labelledby="phone-orders-title">
    <header class="ph-header"><div class="ph-heading"><span class="ph-heading-icon"><i class="fas fa-phone-alt" aria-hidden="true"></i></span><div><h1 id="phone-orders-title">{{ __('phone_orders.title') }}</h1><p>{{ __('phone_orders.subtitle') }}</p></div></div>
        <label class="ph-branch"><i class="fas fa-map-marker-alt" aria-hidden="true"></i><span class="ph-sr-only">{{ __('phone_orders.branch') }}</span><select data-phone-branch><option value="">{{ __('phone_orders.select_branch') }}</option>@foreach($phonePos['branches'] ?? [] as $branch)<option value="{{ $branch['value'] }}" @if((string)($phonePos['selected_branch'] ?? '') === (string)$branch['value']) selected @endif>{{ $branch['name'] }}</option>@endforeach</select></label>
        <div data-phone-orders-branch-slot></div>
        <nav class="ph-view-tabs" aria-label="{{ __('phone_orders.title') }}"><button type="button" data-phone-view="compose" class="is-active" aria-pressed="true"><i class="fas fa-plus" aria-hidden="true"></i>{{ __('phone_orders.new_order') }}</button><button type="button" data-phone-view="orders" aria-pressed="false"><i class="fas fa-motorcycle" aria-hidden="true"></i>{{ __('phone_orders.saved_orders') }}</button></nav>
    </header>
    <div class="ph-notice" data-phone-message role="status" aria-live="polite" hidden><span></span><button type="button" data-phone-retry hidden>{{ __('phone_orders.retry') }}</button></div>
    <nav class="ph-flow"><span data-phone-step-label>{{ __('phone_orders.step_number') }}</span><span data-phone-selected-branch></span><span data-phone-printer-status role="status"></span>@if(!empty($phonePos['receiver_branch']))<a class="ph-printer-setup" href="{{ asset('dashboard/start-branch-pos-printing.cmd') }}" download>{{ __('phone_orders.printer_setup') }}</a>@endif</nav>
    <div class="ph-workspace" data-phone-compose>
        <section class="ph-invoice ph-panel"><header class="ph-panel-heading"><h2><i class="far fa-file-alt" aria-hidden="true"></i>{{ __('phone_orders.invoice') }} <bdi data-phone-edit-number></bdi></h2><button type="button" data-phone-clear>{{ __('phone_orders.clear') }}</button></header><div class="ph-invoice-scroll">
            <div class="ph-lines"><table><colgroup><col class="ph-col-item"><col class="ph-col-quantity"><col class="ph-col-total"><col class="ph-col-remove"></colgroup><thead><tr><th>{{ __('phone_orders.item') }}</th><th>{{ __('phone_orders.quantity') }}</th><th>{{ __('phone_orders.line_total') }}</th><th><span class="ph-sr-only">{{ __('phone_orders.remove') }}</span></th></tr></thead><tbody data-phone-lines></tbody></table><p class="ph-empty" data-phone-empty>{{ __('phone_orders.empty_invoice') }}</p></div>
            <label class="ph-field ph-invoice-note"><span>{{ __('phone_orders.order_notes') }}</span><textarea data-phone-field="notes" rows="2" maxlength="500" placeholder="{{ __('phone_orders.notes_placeholder') }}"></textarea></label>
            <div class="ph-discount" data-phone-discount-wrap hidden><label class="ph-field"><span>{{ __('phone_orders.discount') }}</span><input data-phone-field="discount" value="0.00" inputmode="decimal" maxlength="14"></label><label class="ph-field" data-phone-discount-reason-wrap hidden><span>{{ __('phone_orders.discount_reason') }}</span><input data-phone-field="discount_reason" maxlength="500"></label></div>
            <dl class="ph-totals"><div><dt>{{ __('phone_orders.subtotal') }}</dt><dd><bdi data-phone-total="subtotal">—</bdi></dd></div><div><dt>{{ __('phone_orders.discount') }}</dt><dd><bdi data-phone-total="discount">—</bdi></dd></div><div><dt>{{ __('phone_orders.delivery_fee') }}</dt><dd><bdi data-phone-total="delivery_fee">—</bdi></dd></div><div><dt>{{ __('phone_orders.tax') }} <span data-phone-tax-rate></span></dt><dd><bdi data-phone-total="tax">—</bdi></dd></div><div data-phone-service-row hidden><dt>{{ __('phone_orders.service') }}</dt><dd><bdi data-phone-total="service">—</bdi></dd></div><div class="ph-grand-total"><dt>{{ __('phone_orders.total') }}</dt><dd><strong><bdi data-phone-total="total">—</bdi></strong><small>{{ __('phone_orders.currency') }}</small></dd></div></dl>
            <p class="ph-payment-note"><i class="fas fa-info-circle" aria-hidden="true"></i>{{ __('phone_orders.payment_note') }}</p>
        </div><button type="button" class="ph-save" data-phone-save disabled><i class="far fa-save" aria-hidden="true"></i><span>{{ __('phone_orders.save_order') }}</span><kbd>F9</kbd></button></section>
        <section class="ph-catalog"><header class="ph-catalog-heading"><h2>{{ __('phone_orders.products') }}</h2><label class="ph-search"><i class="fas fa-search" aria-hidden="true"></i><span class="ph-sr-only">{{ __('phone_orders.search') }}</span><input data-phone-search type="search" autocomplete="off" placeholder="{{ __('phone_orders.search') }}"></label></header><div class="ph-categories" data-phone-categories role="group" aria-label="{{ __('phone_orders.products') }}"></div><div class="ph-products" data-phone-products></div><p class="ph-catalog-message" data-phone-catalog-message>{{ __('phone_orders.select_branch') }}</p><nav class="ph-pagination" data-phone-pagination hidden><button type="button" data-phone-page="previous">{{ __('phone_orders.previous') }}</button><span data-phone-page-label></span><button type="button" data-phone-page="next">{{ __('phone_orders.next') }}</button></nav></section>
        <aside class="ph-customer ph-panel"><header class="ph-panel-heading"><h2><i class="far fa-user" aria-hidden="true"></i>{{ __('phone_orders.customer') }}</h2></header><div class="ph-customer-scroll">
            <div data-phone-number-panel><label class="ph-field"><span>{{ __('phone_orders.phone') }}</span><div class="ph-lookup"><input data-phone-field="customer_phone" type="tel" dir="ltr" maxlength="30" autocomplete="off" placeholder="{{ __('phone_orders.phone_placeholder') }}"><button type="button" data-phone-lookup aria-label="{{ __('phone_orders.lookup') }}"><i class="fas fa-search" aria-hidden="true"></i></button></div></label><div data-phone-number-matches><div class="ph-lookup-result" data-phone-lookup-result role="status" hidden></div></div>
            <button type="button" class="ph-step-next" data-phone-next-number>{{ __('phone_orders.next_details') }} <kbd>Enter</kbd></button></div>
            <div data-phone-details-panel><div data-phone-detail-matches></div><div data-phone-branch-slot></div><label class="ph-field"><span>{{ __('phone_orders.name') }}</span><input data-phone-field="customer_name" maxlength="100" autocomplete="off" placeholder="{{ __('phone_orders.name_placeholder') }}"></label>
            <label class="ph-field"><span>{{ __('phone_orders.address') }}</span><textarea data-phone-field="address" maxlength="500" rows="3" placeholder="{{ __('phone_orders.address_placeholder') }}"></textarea></label><div class="ph-address-options"><div id="phone-address-options" data-phone-address-options role="listbox" aria-label="العناوين المقترحة" hidden></div><p data-phone-address-status role="status"></p></div>
            <div class="ph-customer-pair"><label class="ph-field"><span>{{ __('phone_orders.area') }}</span><input data-phone-field="area" maxlength="150" placeholder="{{ __('phone_orders.area_placeholder') }}"></label><label class="ph-field"><span>{{ __('phone_orders.delivery_fee') }}</span><input data-phone-field="delivery_fee" readonly inputmode="decimal" value="0.00" maxlength="14"></label></div><small class="ph-field-hint">{{ __('phone_orders.delivery_fee_hint') }}</small>
            <section class="ph-location"><h3>موقع العميل وتكلفة التوصيل</h3><p data-phone-location-status role="status">اكتب الشارع والمنطقة والمدينة لتحديد موقع العميل تلقائيًا.</p><button type="button" data-phone-locate>بحث العنوان</button><div data-phone-map style="height:280px"></div><p class="ph-map-legend">@if($phonePos['open_phone_maps'])مسار الطريق من الفرع إلى العميل · بيانات OpenStreetMap، البحث Photon، المسار OSRM / FOSSGIS. <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noopener">تصحيح الخريطة</a>@elseاقتراحات Google Maps · راجع دبوس العميل وأكده.@endif</p><div class="ph-customer-pair"><label class="ph-field">خط العرض<input data-phone-lat dir="ltr" inputmode="decimal"></label><label class="ph-field">خط الطول<input data-phone-lng dir="ltr" inputmode="decimal"></label></div><p data-phone-distance aria-live="polite"></p><button type="button" class="ph-confirm-location" data-phone-confirm-location>تأكيد دبوس العميل</button></section>
            <label class="ph-field"><span>شركة التوصيل</span><select data-phone-company><option value="">توصيل الفرع</option></select></label>
            <label class="ph-field"><span>{{ __('phone_orders.customer_note') }}</span><textarea data-phone-field="delivery_notes" rows="2" maxlength="500" placeholder="{{ __('phone_orders.customer_note_placeholder') }}"></textarea></label>
            <button type="button" class="ph-step-next" data-phone-next-details>{{ __('phone_orders.next_products') }} <kbd>Enter</kbd></button></div>
            <div data-phone-customer-summary></div><button type="button" data-phone-edit-customer>{{ __('phone_orders.edit_customer') }}</button><div class="ph-quantity"><div role="group" aria-label="{{ __('phone_orders.quantity') }}"><button type="button" data-phone-mode="piece" aria-pressed="true">{{ __('phone_orders.piece') }}</button><button type="button" data-phone-mode="weight" aria-pressed="false">{{ __('phone_orders.weight') }}</button></div><label class="ph-field"><span>{{ __('phone_orders.quantity') }}</span><input data-phone-quantity inputmode="decimal" value="1" maxlength="10" dir="ltr"></label><p>{{ __('phone_orders.add_hint') }}</p></div>
        </div></aside>
    </div>
    <section class="ph-orders ph-panel" data-phone-orders hidden>
        <header class="ph-panel-heading"><h2><i class="fas fa-motorcycle" aria-hidden="true"></i>{{ __('phone_orders.saved_orders') }}</h2><button type="button" data-phone-refresh><i class="fas fa-sync-alt" aria-hidden="true"></i>{{ __('phone_orders.refresh') }}</button></header>
        <button type="button" data-phone-clear-company @if(empty($phonePos['company_filter'])) hidden @endif>{{ __('phone_orders.all_companies') }}</button>
        <div class="ph-batch-bar"><div><strong data-phone-batch-total>{{ __('phone_orders.select_orders') }}</strong><small>{{ __('phone_orders.same_courier') }}</small></div><button type="button" class="ph-batch-finish" data-phone-batch-finish disabled>{{ __('phone_orders.finish_orders') }}</button></div>
        <div class="ph-delivery-board" data-phone-order-list></div>
    </section>
    <div class="ph-modal-backdrop" data-phone-modal hidden><section class="ph-modal ph-panel" role="dialog" aria-modal="true" aria-labelledby="phone-modal-title" tabindex="-1"><header class="ph-panel-heading"><h2 id="phone-modal-title"></h2><button type="button" data-phone-modal-close aria-label="{{ __('phone_orders.close') }}"><i class="fas fa-times" aria-hidden="true"></i></button></header><div class="ph-modal-content" data-phone-modal-content></div></section></div>
</main></div>
@endsection
@push('custom-js')
<script type="application/json" id="phone-orders-bootstrap">@json($phonePos)</script>
<script type="application/json" id="phone-orders-translations">@json(trans('phone_orders'))</script>
@include('admin.maps.assets')
<script src="{{ asset('dashboard/js/phone-address-search.js') }}?v={{ filemtime(public_path('dashboard/js/phone-address-search.js')) }}"></script>
<script src="{{ asset('dashboard/js/phone-orders.js') }}?v={{ filemtime(public_path('dashboard/js/phone-orders.js')) }}"></script>
@endpush
