'use strict';
const $=id=>document.getElementById(id), D=window.POSDomain;let state,current,category='',busy=false,draftSave=Promise.resolve();
const labels={save:'حفظ طلب',kitchen:'إرسال للمطبخ',bill:'طلب الحساب',sale:'تحصيل نقدي',cancel:'إلغاء'},statusLabels={draft:'مسودة',kitchen:'المطبخ',bill:'الحساب'};
function el(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function message(text){$('message').textContent=text;$('message').hidden=!text;}
async function run(fn){if(busy)return;busy=true;disable();try{await fn();}catch(e){message(e.message);}finally{busy=false;disable();}}
function disable(){for(const id of ['save','kitchen','bill','sale','cancel','new','pair'])$(id).disabled=busy||(!current&&!['new','pair'].includes(id));if(current){$('cancel').disabled=busy||current.status!=='draft';for(const id of ['save','kitchen','bill'])$(id).disabled=busy||current.status==='bill';}}
function applyState(s){state=s;$('connection').textContent=s.online?'متصل بالداشبورد':'يعمل من الجهاز';$('connection').className=s.online?'online':'offline';$('pending').textContent=`${s.counts.pending} عملية منتظرة`;$('pairing').hidden=s.paired||!!s.snapshot;$('workspace').hidden=!s.snapshot;$('branch').textContent=s.snapshot?.branch.name||'ربط برنامج الكمبيوتر';$('cashier').textContent=s.snapshot?.actor.name||'';if(s.error)message(s.error);if(s.snapshot)$('menu-time').textContent='المينيو المحفوظ: '+new Date(s.snapshot.generated_at).toLocaleString('ar-EG');tabs();history();}
function tabs(){const box=$('tabs');box.replaceChildren();for(const o of state?.orders||[]){if(o.status!=='draft'&&o.id!==current?.id)continue;const b=el('button',`${statusLabels[o.status]} ${o.id.slice(0,5).toUpperCase()}`,o.id===current?.id?'active':'');b.onclick=()=>run(()=>select(o.id));box.append(b);if(o.revision===0&&!o.data.items.length){const close=el('button','×');close.setAttribute('aria-label','حذف المسودة الفارغة');close.onclick=()=>run(async()=>{await POS.discard(o.id);if(current?.id===o.id)current=null;applyState(await POS.state());if(!current){if(state.orders[0])await select(state.orders[0].id);else{current=await POS.new();fields();render();applyState(await POS.state());}}});box.append(close);}}}
async function select(id){current=await POS.order(id);fields();render();tabs();disable();}
function fields(){for(const key of ['channel','customer_name','customer_phone','address','table_name','discount','discount_reason','cash_received','notes'])$(key).value=current.data[key]??'';$('delivery').value=D.money(current.data.delivery_cents||0);$('order-number').textContent=current.id.slice(0,8).toUpperCase();$('discount-wrap').hidden=!current.snapshot.can_discount;visibility();}
function visibility(){const channel=$('channel').value;$('table-wrap').hidden=channel!=='dine';for(const id of ['phone-wrap','address-wrap','delivery-wrap'])$(id).hidden=channel!=='phone';}
function collect(){const d={...current.data};for(const key of ['channel','customer_name','customer_phone','address','table_name','discount','discount_reason','cash_received','notes'])d[key]=$(key).value;d.delivery_cents=d.channel==='phone'?D.decimal($('delivery').value):0;return d;}
async function persist(){if(!current)return;await draftSave;current=await POS.update(current.id,collect());}
function queueDraft(){if(!current)return;const id=current.id,data=collect();draftSave=draftSave.catch(()=>{}).then(()=>POS.update(id,data)).then(order=>{if(current?.id===id){current=order;render();}}).catch(error=>{message(error.message);throw error;});draftSave.catch(()=>{});}
function render(){if(!current){$('lines').replaceChildren();return;}const d=current.data,q=D.quote(current.snapshot,d);const box=$('lines');box.replaceChildren();for(let i=0;i<d.items.length;i++){const item=d.items[i],p=current.snapshot.products.find(p=>p.id===item.product_id),v=p.variants.find(v=>v.option_id===item.option_id),row=el('div',undefined,'line'),title=el('div');title.append(el('strong',p.name),el('small',v.label+' · '+(item.quantity_mode==='weight'?'كجم':'قطعة')));const qty=el('input');qty.value=item.quantity;qty.inputMode='decimal';qty.disabled=current.status==='bill';qty.onchange=()=>run(async()=>{const changed=collect();changed.items[i].quantity=qty.value;current=await POS.update(current.id,changed);render();});const remove=el('button','×');remove.disabled=current.status==='bill';remove.onclick=()=>run(async()=>{const changed=collect();changed.items.splice(i,1);current=await POS.update(current.id,changed);render();});row.append(title,qty,el('bdi',D.money(D.quote(current.snapshot,{...d,items:[item],discount:'0.00',delivery_cents:0}).subtotal_cents)),remove);box.append(row);}
for(const [id,key] of Object.entries({subtotal:'subtotal_cents',tax:'tax_cents',total:'total_cents',change:'change_cents'}))$(id).textContent=D.money(q[key]);$('fees').textContent=D.money(q.service_cents+q.delivery_cents);products();for(const key of ['channel','customer_name','customer_phone','address','table_name','discount','discount_reason','notes','delivery'])$(key).disabled=current.status==='bill'||(key==='channel'&&current.revision>0);}
function products(){const snapshot=current?.snapshot||state?.snapshot;if(!snapshot)return;const cat=$('categories');cat.replaceChildren();const all=el('button','جميع الأصناف',category===''?'active':'');all.onclick=()=>{category='';products();};cat.append(all);for(const c of snapshot.categories){const b=el('button',c.name,String(c.id)===category?'active':'');b.onclick=()=>{category=String(c.id);products();};cat.append(b);}const box=$('products');box.replaceChildren();for(const p of snapshot.products){if(category&&String(p.category_id)!==category)continue;if(!$('search').value||p.name.includes($('search').value)){const card=el('div',undefined,'product');card.append(el('strong',p.name));const choice=el('select');for(const v of p.variants){const opt=el('option',v.label+' — '+D.money(v.unit_price_cents)+' ج');opt.value=v.option_id;choice.append(opt);}card.append(choice);const unit=el('select');for(const [value,label] of [['piece','بالقطعة'],['weight','بالكيلو']]){const opt=el('option',label);opt.value=value;unit.append(opt);}unit.value=p.unit==='kg'?'weight':'piece';unit.hidden=!p.variants.some(v=>v.quantity_mode==='select');card.append(unit);const add=el('button','+ إضافة');add.disabled=!current||current.status==='bill';add.onclick=()=>run(async()=>{await persist();const d=collect(),v=p.variants.find(v=>v.option_id===choice.value),mode=v.quantity_mode==='select'?unit.value:v.quantity_mode;const existing=d.items.find(i=>i.product_id===p.id&&i.option_id===choice.value&&i.quantity_mode===mode);if(existing)existing.quantity=(D.decimal(existing.quantity,3)/1000+(mode==='weight'?.25:1)).toFixed(3);else d.items.push({product_id:p.id,option_id:choice.value,quantity_mode:mode,quantity:mode==='weight'?'0.250':'1'});current=await POS.update(current.id,d);render();});card.append(add);box.append(card);}}}
async function action(kind){await persist();message('');const event=await POS.action(current.id,kind,kind==='cancel'?'إلغاء قبل الإرسال':'');current=await POS.order(current.id);if(['kitchen','bill','sale'].includes(kind)){try{await POS.print(event.id);}catch(e){message(e.message+' — يمكنك إعادة الطباعة من سجل العمليات.');}}if(['sale','cancel','kitchen'].includes(kind)){const s=await POS.state();applyState(s);const draft=s.orders.find(o=>o.status==='draft');if(draft)await select(draft.id);else{current=await POS.new();fields();render();applyState(await POS.state());}}else{render();applyState(await POS.state());}POS.sync().catch(e=>message(e.message));}
function history(){const saved=$('saved-orders');saved.replaceChildren();for(const o of state?.orders||[]){const b=el('button',`${statusLabels[o.status]} ${o.data.customer_name||''} — ${o.id.slice(0,8)}`,'saved-order');b.onclick=()=>run(async()=>{await select(o.id);$('history-dialog').close();});saved.append(b);}const box=$('history');box.replaceChildren();for(const r of state?.history||[]){const row=el('div',undefined,'history-row');row.append(el('bdi',new Date(r.event.occurred_at).toLocaleString('ar-EG')),el('span',labels[r.event.kind]+' · '+r.order_id.slice(0,8)),el('bdi',D.money(r.event.data.total_cents)+' ج'),el('span',r.acked?'تمت المزامنة':r.last_error?'تحتاج مراجعة':'منتظرة',r.last_error?'error':''));if(['kitchen','bill','sale'].includes(r.event.kind)){const b=el('button',r.printed?'إعادة طباعة':'طباعة');b.onclick=()=>run(()=>POS.print(r.id));row.append(b);}if(r.last_error){row.title=r.last_error;}box.append(row);}}
for(const id of ['save','kitchen','bill','sale','cancel'])$(id).onclick=()=>run(()=>action(id));
for(const id of ['channel','customer_name','customer_phone','address','table_name','delivery','discount','discount_reason','cash_received','notes'])$(id).onchange=()=>{visibility();try{queueDraft();}catch(e){message(e.message);}};
for(const id of ['customer_name','customer_phone','address','table_name','discount_reason','notes'])$(id).oninput=()=>{try{queueDraft();}catch(e){message(e.message);}};
$('search').oninput=products;$('pair').onclick=()=>run(async()=>{applyState(await POS.pair($('origin').value,$('code').value));if(state.snapshot){current=await POS.new();fields();render();applyState(await POS.state());}});
$('new').onclick=()=>run(async()=>{await persist();current=await POS.new();fields();render();applyState(await POS.state());});$('sync').onclick=()=>run(async()=>{message('');applyState(await POS.sync());});$('dashboard').onclick=()=>run(()=>POS.dashboard());
$('history-button').onclick=()=>{$('history-dialog').showModal();};$('close-history').onclick=()=>$('history-dialog').close();
$('settings').onclick=()=>run(async()=>{const printers=await POS.printers();$('printer').replaceChildren();const def=el('option','طابعة ويندوز الافتراضية');def.value='';$('printer').append(def);for(const p of printers){const o=el('option',p.displayName||p.name);o.value=p.name;$('printer').append(o);}$('printer').value=state.printer;$('settings-dialog').showModal();});$('close-settings').onclick=()=>$('settings-dialog').close();$('printer').onchange=()=>run(()=>POS.printer($('printer').value));$('backup').onclick=()=>run(()=>POS.backup());
POS.onState(applyState);run(async()=>{applyState(await POS.state());if(state.snapshot){const first=state.orders[0];if(first)await select(first.id);else{current=await POS.new();fields();render();applyState(await POS.state());}}});
