@php
    $rtl = app()->getLocale() === 'ar';
    $channel = $receipt['channel'] ?? 'takeaway';
    $context = $receipt['context'] ?? [];
    $unpaid = !empty($receipt['unpaid']);
    $cancelled = ($receipt['status'] ?? '') === 'cancelled';
    $channelTitle = $channel === 'dine' ? __('dining.title') : ($channel === 'phone' ? __('phone_orders.title') : __('takeaway.title'));
    $money = static function ($value) {
        if (!preg_match('/^(-?)([0-9]+)(?:\.([0-9]{1,2}))?$/D', (string)$value, $parts)) return '—';
        return $parts[1].preg_replace('/\B(?=(\d{3})+(?!\d))/', ',', $parts[2]).'.'.str_pad($parts[3] ?? '', 2, '0');
    };
    $paymentLabel = ['cash'=>__('takeaway.cash'), 'card'=>__('takeaway.card'), 'mobile_wallet'=>__('takeaway.wallet'), 'other'=>__('takeaway.other'), 'mixed'=>__('pos_service.mixed'), 'unpaid'=>__('pos_service.unpaid')][$receipt['payment_method']] ?? $receipt['payment_method'];
@endphp
<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ $rtl ? 'rtl' : 'ltr' }}" data-dashboard-receipt="{{ $receipt['print_marker'] ?? 'takeaway' }}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ __('takeaway.current_invoice') }} {{ $receipt['number'] }}</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#edf1f6;color:#172137;font:13px/1.5 Tahoma,Arial,sans-serif}.receipt{width:calc(100% - 24px);max-width:660px;margin:25px auto;padding:24px;background:#fff;border-radius:12px;box-shadow:0 8px 30px #13233a15}.heading{text-align:center;border-bottom:1px solid #d6dce5;padding-bottom:12px}.logo{display:block;width:145px;height:145px;object-fit:contain;margin:0 auto 7px}.heading h1{font-size:18px;margin:4px 0}.heading h2{font-size:16px;margin:4px 0}.heading p{margin:3px 0;font-size:11px;color:#697487}.information{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px 16px;margin:14px 0}.information div{display:flex;gap:7px;min-width:0;overflow-wrap:anywhere}.information dt{font-size:11px;color:#6b778a}.information dd{margin:0;font-size:12px}.full-width{grid-column:1/-1}bdi{unicode-bidi:isolate;direction:ltr;font-variant-numeric:tabular-nums}.number{display:inline-block;white-space:nowrap}table{width:100%;table-layout:fixed;border-collapse:collapse;margin:12px 0}.item-col{width:49%}.quantity-col{width:14%}.price-col{width:17%}.amount-col{width:20%}th,td{padding:8px 4px;border-bottom:1px solid #e3e7ef;text-align:start;vertical-align:top;font-size:11px}th{color:#6b778a}.item-name{overflow-wrap:anywhere}.item-option{display:block;font-size:10px;color:#7b8798;margin-top:2px}.item-unit{display:block;font-size:10px;color:#6b778a}.item-quantity{text-align:center}.item-price,.item-total{text-align:end;white-space:nowrap}.summary{border-top:1px solid #bac5d5;margin-top:14px;padding-top:7px}.summary-row{display:flex;justify-content:space-between;gap:8px;align-items:baseline;padding:4px 0;font-size:12px}.summary-row span:last-child{white-space:nowrap}.grand-total{border-top:2px solid #172137;font-size:18px;font-weight:bold;padding-top:9px;margin-top:7px}.notes{white-space:pre-line;overflow-wrap:anywhere;font-size:11px;background:#fff8e9;padding:9px;margin-top:12px}.notes strong{display:block}.footer{text-align:center;font-size:10px;color:#7b8798;margin:15px 0 0}.controls{display:flex;gap:8px;margin-top:18px}.controls button{border:0;background:#172137;color:#fff;font:inherit;border-radius:5px;padding:8px 14px;cursor:pointer}
@page{size:auto;margin:0}@media print{html,body{width:100%;margin:0;padding:0;background:#fff;color:#000;font-size:10px;line-height:1.4}.receipt{width:100%;max-width:80mm;margin:0 auto;padding:3mm 2mm;border-radius:0;box-shadow:none}.heading{padding-bottom:7px;border-color:#000;break-inside:avoid;page-break-inside:avoid}.logo{width:40mm;max-width:80%;height:auto;aspect-ratio:1;margin:0 auto 4px}.heading h1{font-size:11px;margin:2px 0;overflow-wrap:anywhere}.heading h2{font-size:12px;margin:2px 0}.heading p{font-size:9px;color:#000;margin:2px 0}.information{display:block;margin:8px 0}.information div{margin:3px 0;break-inside:avoid;page-break-inside:avoid}.information dt{font-size:9px;color:#000}.information dd{font-size:10px}.information div{gap:5px}table{margin:8px 0}th,td{font-size:9px;padding:5px 2px;border-color:#aaa}th{color:#000}.item-option,.item-unit{font-size:8px;color:#000}.item-price,.item-total{font-size:8.5px}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}.summary{border-color:#000;padding-top:5px;margin-top:7px;break-inside:avoid;page-break-inside:avoid}.summary-row{font-size:10px;padding:2px 0}.grand-total{font-size:13px;margin-top:5px;padding-top:6px;border-color:#000}.notes{background:#fff;border:1px dashed #888;font-size:9px;padding:5px;margin-top:8px}.footer{font-size:8px;color:#000;margin-top:10px}.controls{display:none!important}}
</style>
</head><body>
<main class="receipt">
<header class="heading"><img class="logo" src="{{ asset('dashboard/branding/fasakhansta-logo-transparent.png') }}" alt="فسخانستا" width="1254" height="1254"><h2>{{ $receipt['branch']['name'] }}</h2>@if(!empty($receipt['branch']['address']))<p>{{ $receipt['branch']['address'] }}</p>@endif @if(!empty($receipt['branch']['phone']))<p><bdi class="number">{{ $receipt['branch']['phone'] }}</bdi></p>@endif<h1>{{ $unpaid ? __('pos_service.unpaid_bill') : __('takeaway.invoice_number') }} <bdi>{{ $receipt['number'] }}</bdi></h1>@if($cancelled)<p><strong>{{ __('pos_service.cancelled') }}</strong></p>@endif</header>
<dl class="information"><div><dt>{{ __('takeaway.date') }}</dt><dd><bdi>{{ \Carbon\Carbon::parse($receipt['created_at'])->timezone('Africa/Cairo')->format('d/m/Y H:i') }}</bdi></dd></div><div><dt>{{ __('takeaway.cashier') }}</dt><dd>{{ $receipt['cashier']['name'] }}</dd></div>@if($channel !== 'takeaway')@include('admin.pos_service.context')@endif<div><dt>{{ __('takeaway.payment_method') }}</dt><dd>{{ $paymentLabel }}</dd></div>@if(!empty($receipt['payment_reference']))<div class="full-width"><dt>{{ __('takeaway.payment_reference') }}</dt><dd>{{ $receipt['payment_reference'] }}</dd></div>@endif</dl>
<table><colgroup><col class="item-col"><col class="quantity-col"><col class="price-col"><col class="amount-col"></colgroup><thead><tr><th>{{ __('takeaway.item') }}</th><th class="item-quantity">{{ __('takeaway.quantity') }}</th><th class="item-price">{{ __('takeaway.price') }}</th><th class="item-total">{{ __('takeaway.line_total') }}</th></tr></thead><tbody>@foreach($receipt['items'] as $item)<tr><td class="item-name">{{ $item['name'] }}@if(!empty($item['option_label']))<span class="item-option">{{ $item['option_label'] }}</span>@endif</td><td class="item-quantity"><bdi class="number">{{ $item['quantity_mode'] === 'piece' ? explode('.', (string)$item['quantity'])[0] : $item['quantity'] }}</bdi><span class="item-unit">{{ __('takeaway.'.($item['quantity_mode'] === 'weight' ? 'kg' : 'piece')) }}</span></td><td class="item-price"><bdi class="number">{{ $money($item['unit_price']) }}</bdi></td><td class="item-total"><bdi class="number">{{ $money($item['total']) }}</bdi></td></tr>@endforeach</tbody></table>
<div class="summary"><div class="summary-row"><span>{{ __('takeaway.subtotal') }}</span><span><bdi>{{ $money($receipt['subtotal']) }}</bdi> {{ __('takeaway.currency') }}</span></div>@if((float)$receipt['discount'] > 0)<div class="summary-row"><span>{{ __('takeaway.discount') }}</span><span><bdi>{{ $money($receipt['discount']) }}</bdi> {{ __('takeaway.currency') }}</span></div>@endif<div class="summary-row"><span>{{ __('takeaway.tax') }} (<bdi>{{ $receipt['tax_rate'] }}%</bdi>)</span><span><bdi>{{ $money($receipt['tax']) }}</bdi> {{ __('takeaway.currency') }}</span></div>@if((float)$receipt['service'] > 0)<div class="summary-row"><span>{{ __('takeaway.service') }}@if(isset($receipt['service_rate'])) (<bdi>{{ $receipt['service_rate'] }}%</bdi>)@endif</span><span><bdi>{{ $money($receipt['service']) }}</bdi> {{ __('takeaway.currency') }}</span></div>@endif
@if((float)($receipt['delivery'] ?? '0') > 0)<div class="summary-row"><span>{{ __('pos_service.delivery') }}</span><span><bdi>{{ $money($receipt['delivery']) }}</bdi> {{ __('takeaway.currency') }}</span></div>@endif<div class="summary-row grand-total"><span>{{ __('takeaway.total') }}</span><span><bdi>{{ $money($receipt['total']) }}</bdi> {{ __('takeaway.currency') }}</span></div>@if($receipt['payment_method'] === 'mixed')@foreach($receipt['payment_breakdown'] ?? [] as $part)<div class="summary-row"><span>{{ ['cash'=>__('takeaway.cash'), 'card'=>__('takeaway.card'), 'mobile_wallet'=>__('takeaway.wallet')][$part['method']] ?? $part['method'] }}</span><span><bdi>{{ $money($part['amount']) }}</bdi> {{ __('takeaway.currency') }}</span></div>@if(!empty($part['reference']))<div class="notes">{{ __('takeaway.payment_reference') }}: {{ $part['reference'] }}</div>@endif
@endforeach
@endif
@if(in_array($receipt['payment_method'], ['cash', 'mixed'], true))<div class="summary-row"><span>{{ __('takeaway.cash_received') }}</span><span><bdi>{{ $money($receipt['cash_received']) }}</bdi> {{ __('takeaway.currency') }}</span></div><div class="summary-row"><span>{{ __('takeaway.change') }}</span><span><bdi>{{ $money($receipt['change']) }}</bdi> {{ __('takeaway.currency') }}</span></div>@endif</div>
@if(!empty($receipt['discount_reason']))<div class="notes"><strong>{{ __('takeaway.discount_reason') }}</strong>{{ $receipt['discount_reason'] }}</div>@endif
@if(!empty($receipt['notes']))<div class="notes"><strong>{{ __('takeaway.order_notes') }}</strong>{{ $receipt['notes'] }}</div>@endif<p class="footer">{{ $channelTitle }}@if($unpaid) · {{ __('pos_service.unpaid') }}@endif</p><div class="controls"><button type="button" onclick="window.print()">{{ __('takeaway.print_invoice') }}</button></div>
</main>
@if(!request()->boolean('dashboard_print'))<script>window.addEventListener('load',function(){window.print();});</script>@endif
</body></html>
